; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/Adafruit ILI9341@^1.6.3
	knolleary/PubSubClient@^2.8
	bodmer/TFT_eSPI @ ^2.5.43

build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1        ; Define o driver correto para o GMT130
  -D TFT_WIDTH=240          ; Resolução de largura do display
  -D TFT_HEIGHT=240         ; Resolução de altura do display
  ; --- Pinos SPI do Hardware (Exemplo para ESP32) ---
  -D TFT_MOSI=23            ; Pino SDA do display
  -D TFT_SCLK=18            ; Pino SCL do display
  -D TFT_DC=2               ; Pino D/C (Data/Command)
  -D TFT_RST=4              ; Pino RES (Reset)
  -D TFT_BL=32              ; Pino BLK (Backlight) - Opcional
  -D TFT_BACKLIGHT_ON=1     ; Liga o backlight em nível lógico ALTO
  ; --- Truque essencial para displays sem pino CS ---
  -D TFT_CS=-1              ; Define CS como -1 para desativar o controle do pino
  ; --- Fontes adicionais ---
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1